"""Add fast.com

Revision ID: 2204b9aa0cfe
Revises: b64d7387753c
Create Date: 2022-08-26 00:42:24.539974

"""
import sqlalchemy as sa
from alembic import op

import medb.model_util


# revision identifiers, used by Alembic.
revision = "2204b9aa0cfe"
down_revision = "b64d7387753c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fast_result",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("time", medb.model_util.TZDateTime(), nullable=False),
        sa.Column(
            "download_mbps",
            sa.Numeric(precision=10, scale=3, asdecimal=False),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fast_result")
    # ### end Alembic commands ###
