"""add_transaction_group

Revision ID: 6b5a13771425
Revises: c632e5b519e4
Create Date: 2023-10-21 15:11:14.365340

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "6b5a13771425"
down_revision = "c632e5b519e4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("leader_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["leader_id"],
            ["transaction_review.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("leader_id"),
    )
    with op.batch_alter_table("transaction_review", schema=None) as batch_op:
        batch_op.add_column(sa.Column("group_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "transaction_review__fk_group_id",
            "transaction_group",
            ["group_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transaction_review", schema=None) as batch_op:
        batch_op.drop_constraint(
            "transaction_review__fk_group_id", type_="foreignkey"
        )
        batch_op.drop_column("group_id")

    op.drop_table("transaction_group")
    # ### end Alembic commands ###
