"""Add user settings table

Revision ID: 7756e8ba9852
Revises: 6b5a13771425
Create Date: 2024-06-09 16:30:56.201329

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7756e8ba9852"
down_revision = "6b5a13771425"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_shiso_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("scheduled_sync", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_shiso_settings")
    # ### end Alembic commands ###
