"""Remove unused Balance table

Revision ID: 9dc843a8faeb
Revises: 1b90fe05d0c6
Create Date: 2022-01-03 21:19:35.637164

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "9dc843a8faeb"
down_revision = "1b90fe05d0c6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("account_balance")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_balance",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("account_id", sa.INTEGER(), nullable=False),
        sa.Column("amount", sa.NUMERIC(precision=16, scale=3), nullable=False),
        sa.Column("date", sa.DATE(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["user_plaid_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "date"),
    )
    # ### end Alembic commands ###
