"""Add IPv6 fields

Revision ID: b64d7387753c
Revises: da613317f69e
Create Date: 2022-08-25 18:21:49.841969

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "b64d7387753c"
down_revision = "da613317f69e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ipcheck_result", schema=None) as batch_op:
        batch_op.alter_column(
            "ipv4", existing_type=sa.VARCHAR(length=15), nullable=True
        )

    with op.batch_alter_table("ping_result", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "v6_ping_ms",
                sa.Numeric(precision=7, scale=3, asdecimal=False),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ping_result", schema=None) as batch_op:
        batch_op.drop_column("v6_ping_ms")

    with op.batch_alter_table("ipcheck_result", schema=None) as batch_op:
        batch_op.alter_column(
            "ipv4", existing_type=sa.VARCHAR(length=15), nullable=False
        )

    # ### end Alembic commands ###
