"""Add Subscription table

Revision ID: e3745a3d757f
Revises: 9dc843a8faeb
Create Date: 2022-01-05 22:40:27.156865

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e3745a3d757f"
down_revision = "9dc843a8faeb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("regex", sa.String(), nullable=False),
        sa.Column("is_new", sa.Boolean(), nullable=False),
        sa.Column("is_tracked", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["user_plaid_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table(
        "user_plaid_transaction", schema=None
    ) as batch_op:
        batch_op.add_column(
            sa.Column("subscription_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            "transaction__fk_subscription_id",
            "subscription",
            ["subscription_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "user_plaid_transaction", schema=None
    ) as batch_op:
        batch_op.drop_constraint(
            "transaction__fk_subscription_id", type_="foreignkey"
        )
        batch_op.drop_column("subscription_id")

    op.drop_table("subscription")
    # ### end Alembic commands ###
