"""Initial migration

Revision ID: ebb6a380f885
Revises:
Create Date: 2021-10-21 18:26:33.131048

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "ebb6a380f885"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "transaction_review", ["transaction_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transaction_review", type_="unique")
    # ### end Alembic commands ###
